In [1]:
from transformers import pipeline

classifier = pipeline('text-to-audio')

res = classifier('hello-world')

print(res)

d:\Machine_Learning\intro-to-llm\llmenv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
No model was supplied, defaulted to suno/bark-small and revision 645cfba (https://huggingface.co/suno/bark-small).
Using a pipeline without specifying a model name and revision in production is not recommended.
d:\Machine_Learning\intro-to-llm\llmenv\lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `

{'audio': array([[ 0.00192072,  0.00134375,  0.00127502, ..., -0.00068161,
        -0.00058366, -0.00048353]], dtype=float32), 'sampling_rate': 24000}


In [2]:
res['audio']

array([[ 0.00192072,  0.00134375,  0.00127502, ..., -0.00068161,
        -0.00058366, -0.00048353]], dtype=float32)

In [3]:
import soundfile as sf



In [4]:
sf.write('namaste.wav', res['audio'][0], res['sampling_rate'])

In [16]:
import numpy 
numpy.sin(numpy.linspace(0, 3000, 20000))

array([0.        , 0.14944555, 0.29553454, ..., 0.497747  , 0.36253982,
       0.21918997])

In [21]:
res['audio'][0]

array([0.00084459, 0.00033031, 0.00032517, ..., 0.00029121, 0.00029206,
       0.00029351], dtype=float32)